# Copyright 2023-2026 Red Hat, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Go tests

on:
  workflow_call:

    inputs:
      coverage:
        description: 'Check the code coverage'
        type: boolean
        default: true

      coverage_threshold:
        description: 'Coverage threshold'
        required: false
        type: number
        default: 0

jobs:
  gotests:
    runs-on: ubuntu-latest
    container:
        image: registry.access.redhat.com/ubi9/go-toolset:latest
    name: Go tests
    steps:
      - uses: actions/checkout@v6
      - name: Unit tests
        run: make test
      
      - name: Prepare workflow
        if: inputs.coverage == true
        uses: actions/checkout@v6
        with:
          repository: RedHatInsights/processing-tools
          path: processing-tools

      - name: Retrieve code coverage
        if: inputs.coverage == true
        env:
          COV_THRESHOLD: ${{ inputs.coverage_threshold }}
        run: ./processing-tools/go-checkers/check_coverage.sh

      - name: Push coverage report to Codecov
        if: inputs.coverage == true
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
